# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://bitcloud2.github.io/pomerantz/"

git_url = "https://github.com/bitcloud2/pomerantz/tree/main/"

def custom_doc_links(name): return None
