# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "01_boostmonodepth_utils.ipynb",
         "HelloSayer": "01_boostmonodepth_utils.ipynb"}

modules = ["main.py",
           "core.py",
           "boostmonodepth_utils.py"]

doc_url = "https://bitcloud2.github.io/pomerantz/"

git_url = "https://github.com/bitcloud2/pomerantz/tree/main/"

def custom_doc_links(name): return None
